[package]
name = "cat_facts"
version = "0.1.0"
authors = ["Afel <prteza@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5.0"